Create SECURITY.md
DevCrew-io/2checkout-flutter pull request #6
Opened 2023-09-13 07:29 UTC by arslandevcrew

2023-09-13 08:26 UTC, WaseemAbbas-DevCrew requested changes

2023-09-13 08:26 UTC, WaseemAbbas-DevCrew commented on SECURITY.md
> +please notify us immediately by sending an email to arslan.khan@devcrew.io.
please use` hello@devcrew.io`

2023-09-13 14:31 UTC, arslandevcrew commented on SECURITY.md
> +please notify us immediately by sending an email to arslan.khan@devcrew.io.
updated

2023-09-14 08:21 UTC, WaseemAbbas-DevCrew approved these changes

2023-09-14 08:25 UTC, merged